### ISSUE TITLE
Problems to run the program

### ISSUE THREAD

**Issue by kevinlemon** [mancinimassimiliano/DeepNCM#1]
This program cannot run.

**Comment by mancinimassimiliano** [comment]
Hi @kevinlemon. I had no problems on running the code on different PCs. The only prerequisite is having pytorch>0.4.0 installed. Could you be more specific about your problem?

**Comment by kevinlemon** [comment]
Thank you for your reply.
My pytorch version is 0.4.0, python 3.6.
There are 3 types of errors when I run the "training_ncm.py"
(1) Inconsistent use of tabs and spaces in indentation error occurs in line 97, 104, 114, 121, 139 and so on.
(2) """   File "/home/uwb/Documents/DeepNCM-master/utils.py", line 45, in <module>
    _, term_width = os.popen('stty size', 'r').read().split()

ValueError: not enough values to unpack (expected 2, got 0) """
(3)""" During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/uwb/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/uwb/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/uwb/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4712bd780>: Failed to establish a new connection: [Errno 111] Connection refused',))"""

I tried to modify these errors, but after training phase, all I got is the following information:
"""
TRAINING
 [>................................................................]  Step: 3s468ms | Tot: 0ms | Loss: 2.185 | Acc: 17.188% (22/128)
TEST
 [>................................................................]  Step: 218ms | Tot: 0ms | Loss: 2.019 | Acc: 31.000% (31/100)Exception in user code:
"""

**Comment by mancinimassimiliano** [comment]
(1) Ok, one thing I forgot to mention in the doc is that I used python 2.7 and this may cause the problems. 
(2-3) The error seems linked to the visualization part. If you have visdom installed, is the server running? Otherwise, have you tried running the code with the `--no_vis ` argument?

**Comment by kevinlemon** [comment]
Thank you for your help. I will try it.

**Comment by mancinimassimiliano** [comment]
Hi @kevinlemon, have you found a fix for the problem?
